### ISSUE TITLE
Class 'CauseLabs\ResourceIndexLink\ResourceIndexLink' not found

### ISSUE THREAD

**Issue by XGhozt** [causelabs/resource-index-link#1]
Not sure what the issue is but I cannot get this package to work. I think there might be a typo in a namespace somewhere.

**Comment by XGhozt** [comment]
Yeah, I just noticed your other commit about the typo with the letter `L` in `Causelabs`. I changed all the namespaces to `Causelabs` instead of `CauseLabs` and that fixed it. Can you confirm this is the problem?

**Comment by rick-hidef** [comment]
Yep, that appears the problem. This should now be fixed.
