### ISSUE TITLE
Hardcoded /nova/ link in components

### ISSUE THREAD

**Issue by XGhozt** [causelabs/resource-index-link#2]
This needs to be taken out since this is customizable. It should pull the value from config/nova.php `APP_URL`.

**Comment by rick-hidef** [comment]
Good catch! I have modified the code to pull in the base path from the Nova config.

**Comment by XGhozt** [comment]
@rick-hidef -- this is still broken. If the configured app URL is just "/", then we get two slashes which makes the browser treat it as an external URL. 😄

**Comment by rick-hidef** [comment]
@XGhozt  Gotcha. Just pushed a fix for that.
