### ISSUE TITLE
Link should use router-link component

### ISSUE THREAD

**Issue by XGhozt** [causelabs/resource-index-link#3]
The way it is now, it's an anchor which causes the whole page to be reloaded. We should be using the `router-link` component to VueJS loads the next page correctly.

**Comment by rick-hidef** [comment]
I'm out of town for the rest of the week, but will look at this next week. It's not quite that straightforward, since the control supports the ability to open in a new tab, but `router-link` does not.

**Comment by XGhozt** [comment]
Does this work? https://stackoverflow.com/questions/40015037/can-vue-router-open-a-link-in-a-new-tab/49654382#49654382

**Comment by rick-hidef** [comment]
Thanks for the info. This is now implemented in 0.2.8.

**Comment by rick-hidef** [comment]
Thanks for the info. This is now implemented in 0.2.8.

**Comment by XGhozt** [comment]
Yay!
